version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/sandboxygn-online-courses
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      runas: ubuntu
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: ubuntu
